name: instaseg
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py37h06a4308_0
  - cudatoolkit=11.0.221=h6bb024c_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9b=h024ee3a_2
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.3=h7f8727e_2
  - ninja=1.10.2=py37hd09550d_3
  - numpy-base=1.21.2=py37h79a1101_0
  - olefile=0.46=py37_0
  - openssl=1.1.1l=h7f8727e_0
  - pillow=8.4.0=py37h5aabda8_0
  - pip=21.2.2=py37h06a4308_0
  - python=3.7.11=h12debd9_0
  - pytorch=1.7.1=py3.7_cuda11.0.221_cudnn8.0.5_0
  - readline=8.1=h27cfd23_0
  - setuptools=58.0.4=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.37.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.7.2=py37
  - torchvision=0.8.2=py37_cu110
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==1.0.0
    - cachetools==4.2.4
    - charset-normalizer==2.0.10
    - cloudpickle==2.0.0
    - cycler==0.11.0
    - cython==0.29.26
    - fonttools==4.28.5
    - future==0.18.2
    - fvcore==0.1.1.dev200512
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - grpcio==1.43.0
    - idna==3.3
    - importlib-metadata==4.10.0
    - iopath==0.1.9
    - kiwisolver==1.3.2
    - markdown==3.3.6
    - matplotlib==3.5.1
    - mock==4.0.3
    - numpy==1.21.5
    - oauthlib==3.1.1
    - opencv-python==4.5.5.62
    - packaging==21.3
    - polygon3==3.0.9.1
    - portalocker==2.3.2
    - protobuf==4.0.0rc2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.3
    - pydot==1.4.2
    - pyparsing==3.0.6
    - python-dateutil==2.8.2
    - python-levenshtein==0.12.2
    - pyyaml==6.0
    - requests==2.27.1
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - shapely==1.8.0
    - tabulate==0.8.9
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tqdm==4.62.3
    - urllib3==1.26.8
    - werkzeug==2.0.2
    - wheel==0.37.1
    - yacs==0.1.8
    - zipp==3.7.0
prefix: /home/sbiswas/miniconda3/envs/instaseg
